hipchat:
    username: 1_22@chat.btf.hipchat.com
    password: zoolander bot
    server: hipchat.pamlabdev.com
    conf: conf.btf.hipchat.com
    nick: Zoolander
    botname: '@Zoolander'
    rooms: 
        - 1_bottest
#        - 1_#dev

bamboo:
    url_base: http://build.pldev.local:8085/rest/api/latest
    username: zoolander
    password: zoolander bot

database:
    name: 'hipbot.db'

