hipchat:
    username: username
    password: password
    server: chat.hipchat.com
    conf: conf.hipchat.com
    nick: My Nickname
    botname: '@mynick'
    rooms: 
        - room1
        - room2

bamboo:
    url_base: http://build:8085/rest/api/latest
    username: username
    password: password

database:
    name: 'hipbot.db'

meme:
    post_url: https://api.imgflip.com/caption_image
    username: username 
    password: password
